### ISSUE TITLE
Request for a TLE.txt

### ISSUE THREAD

**Issue by maebli** [LacunaSpace/orbit-tools#1]
Hello
can you add the TLE.txt for the satellite available for development?

**Comment by jkoops** [comment]
Hi - the TLE needs to be refreshed periodically (typically every few days), so there's no point adding it to the source-code. However, you can download it yourself from a website such as SpaceTrack at: https://www.space-track.org/basicspacedata/query/class/tle_latest/ORDINAL/1/NORAD_CAT_ID/47948/orderby/NORAD_CAT_ID/format/tle (you will need to create a free account on that website). In the URL, `47948` is the catalog ID of the LS2B satellite - to get the TLE of any other satellite, simply change the catalog ID.

Do keep in mind that LS2B is not in receive mode 100% of the time - therefore, the satellite being visible from a certain location does not necessarily mean you can send messages to it. The passes predicted by the dashboard (https://dashboard.lacuna.space) take this into account - during a pass predicted by the dashboard the satellite is always in receive mode.

**Comment by jkoops** [comment]
Add example on fetching TLEs to documentation

**Comment by maebli** [comment]
Thanks!
